name: deploy authenticate
on:
  push:
    branches: [ master ]
    paths:
        - 'backend/**'
        - 'config/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Replace SERVICE arg in dockerfile
        run:  |
          sed -i 's/${SERVICE}/authenticate/g' Dockerfile
        env:
            SERVICE: authenticate
      - name: Setup - gcloud / gsutil
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.ACTIONS_SERVICE_ACC }}
          export_default_credentials: true
      - name: Set default project
        run: |
          gcloud config set core/project joshcarp-it-project
          gcloud auth configure-docker
          gcloud config set run/region us-central1
      - name: Build
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/joshcarp-it-project/authenticate:$GITHUB_SHA"
      - name: Deploy
        run: |-
          gcloud run deploy "authenticate" \
            --quiet \
            --region "us-central1" \
            --image "gcr.io/joshcarp-it-project/authenticate:$GITHUB_SHA" \
            --platform "managed" \
            --service-account github-actions@joshcarp-it-project.iam.gserviceaccount.com \
            --allow-unauthenticated
      - name: Set permissions
        run: |-
          gcloud run services add-iam-policy-binding authenticate \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --platform managed

